default_sl = 0.02

[risk_tiers]
# as percentage points
a = "20%"
b = "8%"
c = "3%"
d = "1%"
e = "0.25%"

[[exchanges]]
name = "binance"
key = { env = "BINANCE_TIGER_FULL_PUBKEY" }
secret = { env = "BINANCE_TIGER_FULL_SECRET" }

[[exchanges]]
name = "bybit"
key = { env = "QUANTM_BYBIT_SUB_PUBKEY" }
secret = { env = "QUANTM_BYBIT_SUB_SECRET" }

[[exchanges]]
name = "mexc"
key = { env = "MEXC_READ_PUBKEY" }
secret = { env = "MEXC_READ_SECRET" }
